### ISSUE TITLE
obtaining all reads mapping to a given bin

### ISSUE THREAD

**Issue by rikander** [meren/anvio#173]
It would be lovely to be able to pull out all of the reads that mapped to a given bin so that you can do things further downstream like reassembly, or combining those reads with SAG reads, or whatever.

In general, having command-line access to the database containing the bins, the contigs, the splits, the reads, the average coverage per bin, average coverage per split, the normalization factors, etc. would make it much easier for us to access the data and then write our own scripts for whatever specific analyses we want to do. (This is presuming you have a SQL database containing this already, but maybe not-- I have no idea how hard this would be to implement.)

**Comment by meren** [comment]
OK. We have the first version of the client, `anvi-get-short-reads-from-bam`, to get short reads back from BAM files. It is pretty talented, but it needs some testing.

~~~ bash
$ anvi-get-short-reads-from-bam --help
usage: anvi-get-short-reads-from-bam [-h] -p PROFILE_DB -a ANNOTATION_DB -c
                                     COLLECTION-ID [-b BIN_ID] [-B BINS FILE]
                                     [-o OUTPUT_FILE_NAME] [--debug]
                                     BAM FILE[S] [BAM FILE[S] ...]

Get short reads back from a BAM file.

positional arguments:
  BAM FILE[S]           BAM file(s) to access to recover short reads

optional arguments:
  -h, --help            show this help message and exit
  -p PROFILE_DB, --profile-db PROFILE_DB
                        Profile database.
  -a ANNOTATION_DB, --annotation-db ANNOTATION_DB
                        Annotation database.
  -c COLLECTION-ID, --collection-id COLLECTION-ID
                        Collection id to look for bins.
  -b BIN_ID, --bin-id BIN_ID
                        A bin to analayze (you either use this, or use a file
                        to list each bin id you prefer to analyze).
  -B BINS FILE, --bin-ids-file BINS FILE
                        Text file for bins (each line should be a bin id).
  -o OUTPUT_FILE_NAME, --output-file-name OUTPUT_FILE_NAME
                        Output directory
  --debug               Extra outputs for debugging. I would not use it if I
                        were you.
~~~

And here is an example from the mini_test:

~~~ bash
$ anvi-get-short-reads-from-bam -p test-output/204-MERGED/PROFILE.db \
                                                    -a test-output/ANNOTATION.db \
                                                    -c CONCOCT \
                                                    -b Bin_2 \
                                                    -o short_reads_for_Bin_2.fasta \
                                                    test-output/*bam

Input BAM file(s) ............................: 204-6M.bam, 204-7M.bam, 204-9M.bam
Collection ID ................................: CONCOCT
Bin(s) .......................................: Bin_2
Number of splits .............................: 17
Num reads stored .............................: 23,338
FASTA output .................................: short_reads_for_Bin_2
~~~

Please let me know if you end up testing it.

At this point we are only working with individual reads and stores a FASTA file, but I believe it is going to be critical to add support for paired-end reads and stores results in FASTQ files.

**Comment by ntseng57** [comment]
Hi Meren, 

Does the current version of Anvi'o support storing as FASTQ file? 

Thank you,
Nancy

**Comment by meren** [comment]
No, unfortunately. It is rather easy to convert FASTA files to FASTQ files,
and we never run into a situation we needed FASTQ files.

Why do you need it?

**Comment by ntseng57** [comment]
Hi Meren,

Thank you for your reply. 

1) I was thinking to export short reads and then do re-assembly of some bins through metaspades. I have several different profiles of the same samples due to using spades and megahit. I'm not sure if this is ok, but I wanted to re-assemble similar bins (called by taxonomy) from these different profiles.

2) I'm going to refine some SAGs individually on Anvi'o and then export short reads to assemble on spades (also will do co-assembly on spades later).

What do you think? I think the main issue is that spades uses only fastq. I got this error when I tried today for my metagenome samples. 

Thanks!
Nancy
