### ISSUE TITLE
Can't get completeness/contamination tables

### ISSUE THREAD

**Issue by bowmanjeffs** [meren/anvio#186]
After launching interactive view and loading bin collection I can see statistics for completeness/contamination but clicking those buttons, or the splits button, gets no response from browser.  When I launch the interactive view I get these errors, which may be related (however interactive view proceeds to launch just fine).  I'm using the latest version of Chrome available for Ubuntu.

grep: write error
[15688:15688:0807/113934:ERROR:gl_surface_glx.cc(348)] GLX 1.3 or later is required.
[15688:15688:0807/113934:ERROR:gl_surface_x11.cc(56)] GLSurfaceGLX::InitializeOneOff failed.
[15688:15688:0807/113934:ERROR:gpu_child_thread.cc(163)] Exiting GPU process due to errors during initialization

**Comment by meren** [comment]
Hi Jeff,

This is interesting. @ozcanesen, do you have any idea?

I wonder whether this could be related to your Chrome build. Here is mine:

![image](https://cloud.githubusercontent.com/assets/197307/9142676/50ea86ec-3d0f-11e5-8676-e745f15cd5f7.png)

Thanks,

**Comment by bowmanjeffs** [comment]
Glad I can continue to provide interesting problems...

Same build (Version 44.0.2403.125 (64-bit)).

**Comment by meren** [comment]
:)

@ozcanesen can you please look into this on an Ubuntu computer?

**Comment by ozcanesen** [comment]
I couldn't reproduce it on my ubuntu laptop, going to try it in vm with fresh install.

@bowmanjeffs: can you see anything in javascript console (ctrl+shift+J / cmd+option+J) when you press splits/completeness buttons?

**Comment by bowmanjeffs** [comment]
ctrl+shift+J brings up a save file (save webpage) dialogue for me ...

**Comment by ozcanesen** [comment]
@bowmanjeffs Sorry, You can open console using Menu > More Tools > Javascript Console, also.

**Comment by bowmanjeffs** [comment]
In the console I see some commands associated with generating the tree:

tree_draw [tooltips]: 0.228 seconds (0.228 seconds since beginning)
utils.js:229 tree_draw [normalizations]: 0.119 seconds (0.347 seconds since beginning)
utils.js:229 tree_draw [barsizes]: 0.876 seconds (1.22 seconds since beginning)
utils.js:229 tree_draw [done]: 5.13 seconds (6.36 seconds since beginning)
treelib.js:2383 [info] Leaf count: 9589
treelib.js:2384 [info] Object count in tree (with guide lines): 33560
treelib.js:2385 [info] Total objects in SVG: 93354

Clicking the buttons does not generate any new entries in the log.

**Comment by meren** [comment]
Jeff, this is very weird. Because if this is a javascript issue there must be something in the logs :/

Do you mind taking a screenshot of where are you clicking on the page? I am sorry, we are a bit confused with this issue :)

**Comment by bowmanjeffs** [comment]
I thought a video would be more informative...

http://www.polarmicrobes.org/wp-content/uploads/2015/08/bin_button.mp4

Note that I'm viewing with Xming, but the behavior is the same if I'm sitting at the console.

**Comment by ozcanesen** [comment]
@bowmanjeffs Hey thank you this is very informative, the results appear in bottom of the same tab like this
<img width="492" alt="screen shot 2015-08-09 at 9 38 59 am" src="https://cloud.githubusercontent.com/assets/940884/9155097/a3c416be-3e7a-11e5-88c7-dd332c181d62.png">

**Comment by meren** [comment]
Thank you for sending this, Jeff.

This obviously is a usability issue, @ozcanesen :/ We can't really expect people to go all the way down to the page to see these results. But we also have links to click down in the table, so we need to keep it as well.

I think the solution is a mouse-over popup that shows the content of that table, and if the user clicks on the button, the page scrolls down to the table area. Does it make sense? Do you think it is a good solution?

**Comment by bowmanjeffs** [comment]
Thanks!  Don't know how I missed that...

Meren - I think what you propose is a good solution.  It is a little cumbersome to keep scrolling to end if there are many bins.

**Comment by meren** [comment]
Yes. It is an ancient struggle to keep usability and functionality keep up with each other.

@ozcanesen, another solution could be showing a draggable modal window.
