### ISSUE TITLE
control for minimum split position coverages when creating variability profiles

### ISSUE THREAD

**Issue by tdelmont** [meren/anvio#196]
Hi,
I am working on variability profiles and suggests that we add a control for minimum position coverage values in the dataset (might be for all samples or a selection of samples).

I want to discard detected variable positions where coverage is below a given number in some samples. I think that many times the variability is not detected simply due to a lack of coverage and I want to avoid the bias.

Hope it makes sense.

Also, it would be good to offer the possibility of getting the coverage values (in multiple samples) of a list of split positions as a matrix table. Maybe I missed it but could not get that with anvi'o (could have been an alternative for me to remove the unwanted positions from the variability analysis later on)

Tom

**Comment by meren** [comment]
This is a good idea. One idea per issue! :) Whenever a paragraph starts with "also", it is a good indication that it is a new idea and should be mentioned in separate issues.

I will work on the first one soon. Currently we are very busy with some other cute thing.

**Comment by meren** [comment]
The new parameter is this: `--min-coverage-in-each-sample`.

Here is an excerpt from the help menu:

~~~ bash
  --min-coverage-in-each-sample INT
                        Minimum coverage of a given variable nucleotide
                        position in all samples. If a nucleotide position is
                        covered less than this value even in one sample, it
                        will be removed from the analysis. Default is 0.
~~~
