### ISSUE TITLE
Error in mini test

### ISSUE THREAD

**Issue by jgabriel1206** [meren/anvio#199]
Hi Meren

I was trying to install anvio in my computer using the safe mode. I checked/installed all the dependencies but I got this error when I ran the mini test:

usage: anvi-init-bam [-h] [--sorted] [-o OUTPUT_FILE] BAM_FILE
anvi-init-bam: error: unrecognized arguments: --output-file-prefix test-output/204-6M

Do you know how can I fix this?

Thanks

**Comment by meren** [comment]
Hi,

We have seen this before when the installed version of anvi'o was behind the codebase where the tests were obtained from. Please see this one and it will hopefully make more sense: #190.

If you can tell me what is the output you get when you type this, I can be a bit more helpful :)

~~~ bash
anvi-profile --version
~~~

Thanks,

**Comment by jgabriel1206** [comment]
Thanks Meren

This is the version I have:

Anvi'o version ...............................: 1.0.2
Annotation DB version ........................: 3
Profile DB version ...........................: 5

I followed your directions in #190, I got a couple of warnings and a new error:

# Re-populating the genes tables in the annotation database using the recovered matrix file with 'default_matrix' parser ...
#
#
WARNING
===============================================
Previous genes annotation data from "default_matrix" will be replaced with the
incoming data


ERROR:

# Populating collections tables using mock clustering results for CONCOCT ...
#
#

./run_mini_test.sh: line 51: anvi-populate-collections-table: command not found


Thanks again

Gabriel

**Comment by meren** [comment]
So you have 1.0.2. Perfect! Can you run these commands, please:

~~~ bash
$ wget https://github.com/meren/anvio/archive/v1.0.2.tar.gz
$ tar -zxvf v1.0.2.tar.gz
$ cd anvio-1.0.2/tests/
$ ./run_mini_test.sh
~~~

This will give you the tests directory that matches to the installed version you have.

Meanwhile I will start thinking a better way of handling this problem :)

Thanks you for your patience.

**Comment by jgabriel1206** [comment]
It's working now.
thank you very much
