### ISSUE TITLE
Killing the SUMMARY.cp (with fire .. and HDF5).

### ISSUE THREAD

**Issue by meren** [meren/anvio#202]
SUMMARY.cp and SUMMARY/ directory are generated after every profilining operation, and they are merged when the user runs anvi-merge. SUMMARY.cp is a serialized Python dictionary that simply keeps the relative path for each split and resolves to another serialized file under the SUMMARY directory. For instance, this is what you see in the output directory when you run the `mini_test`:

~~~ bash
anvio/tests/sandbox/test-output/204-MERGED $ ls
PROFILE.db  RUNINFO.mcp SUMMARY     SUMMARY.cp
meren ~/Desktop/MBL/anvio/tests/sandbox/test-output/204-MERGED $ ls SUMMARY
000001.cp 000004.cp 000007.cp 000010.cp 000013.cp 000016.cp 000019.cp 000022.cp 000025.cp 000028.cp 000031.cp 000034.cp 000037.cp 000040.cp 000043.cp 000046.cp 000049.cp 000052.cp 000055.cp
000002.cp 000005.cp 000008.cp 000011.cp 000014.cp 000017.cp 000020.cp 000023.cp 000026.cp 000029.cp 000032.cp 000035.cp 000038.cp 000041.cp 000044.cp 000047.cp 000050.cp 000053.cp 000056.cp
000003.cp 000006.cp 000009.cp 000012.cp 000015.cp 000018.cp 000021.cp 000024.cp 000027.cp 000030.cp 000033.cp 000036.cp 000039.cp 000042.cp 000045.cp 000048.cp 000051.cp 000054.cp 000057.cp
anvio/tests/sandbox/test-output/204-MERGED $
~~~

And each of these serialized files in the SUMMARY directory, holds a data structure like this (an example from a random contig in INFANT GUT data):

~~~ python
>>> import anvio.dictio as d

>>> a = d.read_serialized_object('SUMMARY/001725.cp')

>>> a.keys()
>>>
['DAY_17A',
 'DAY_17B',
 'DAY_18',
 'DAY_19',
 'DAY_15B',
 'DAY_22A',
 'DAY_16',
 'DAY_15A',
 'DAY_23',
 'DAY_22B',
 'DAY_24']

>>> a['DAY_17A'].keys()
>>> ['variability', 'coverage', 'competing_nucleotides']

>>> a['DAY_17A']['variability']
>>>
[0,
 0,
 0,
 0,
...
 0,
 0.4,
 0,
 0,
 0,
 0,
 ...]

>>> len(a['DAY_17A']['variability'])
>>> 20000

>>> a['DAY_17A']['competing_nucleotides']
>>>
{816: 'CA',
 3765: 'TC',
 3815: 'TA',
 4915: 'GT',
 6082: 'CA',
 6638: 'CA',
 11209: 'GT',
 11543: 'AT',
 11580: 'GC',
 11865: 'TG',
 14027: 'CA',
 17552: 'TG',
 19089: 'AT'}

>>> len(a['DAY_17A']['coverage'])
>>> 20000

>>> a['DAY_17A']['coverage'][0:20]
>>>
[12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 16]
~~~

This information is kept per split per sample and becomes very handy when you want to go back to raw coverage values (which we often do when we right click a split and 'inspect' .. in that point in time all coverage values and variability information is being pulled from this data structure).

The problem with this design is that it generates many many tiny files on the file system (as many as the number of splits for each project, to be precise), and this creates a great deal of I/O overhead when copying or moving these outputs around.

Also this is a pretty weak design and can be done much better with a database setting.

So I decided to kill the SUMMARY.cp and its companion SUMMARY directory. It is very sad, of course. But we sooner or later learn to deal with this type of stuff.

There are two essential things those serialized files hold: coverage values, and variability stats per split in a sample or across samples (depending on whether we are looking into a single or merged profile database). In fact the information about variability is already stored in the database in our good old `variable_positions` table (de8efabfc0c262c24d265d2cdc0a2139769333ef), so one way or another the variability information stored in these serialized files can be retrieved from the database. The only thing to retain is the coverage values, and for which I decided to create a new table to store coverage values within profile databases to solve this once and for all.

**Comment by meren** [comment]
This change will require an increment in the version number of the profile database. The upgrade, and populating the coverages table will possible with this new script (93a76f3259767d88a0f21a543f98c660edec6c4c):

```
anvi-script-upgrade-profile-db-v6-to-v7 -p PROFILE.db
```

**Comment by meren** [comment]
In theory I am almost done with this, but in practice I realized that the size of the profile database goes crazy when I started store coverage values in it in binary format.

Here is the space serialized objects took on disk for the infant gut dataset:

~~~ python
$ du -sh SUMMARY.cp SUMMARY/
 56K	SUMMARY.cp
 98M	SUMMARY/
~~~

And this is the size of the PROFILE database for infant gut, before carrying the information above into it:
~~~ python
$ ls -lh PROFILE.db.bak
-rw-r--r--  1 meren  staff    27M Sep 17 18:35 PROFILE.db.bak
~~~

Finally, this is the new database after the switch:

~~~ python
$ ls -lh PROFILE.db
-rw-r--r--  1 meren  staff   816M Sep 18 09:41 PROFILE.db
~~~

From 27Mb to 816Mb by adding only ~100Mb worth of information in serialized format :/

And here is the contribution of each table to the profile database:

~~~ python
$ sqlite3_analyzer PROFILE.db | head -n 100

(...)

*** Page counts for all tables with their indices *****************************

SPLIT_COVERAGE_VALUES............................. 807424      96.7%
GENE_COVERAGES.................................... 9604         1.2%
VARIABLE_POSITIONS................................ 6327         0.76%
CLUSTERINGS....................................... 829          0.099%
ABUNDANCE_CONTIGS................................. 689          0.083%
MEAN_COVERAGE_CONTIGS............................. 689          0.083%
NORMALIZED_COVERAGE_CONTIGS....................... 689          0.083%
STD_COVERAGE_CONTIGS.............................. 689          0.083%
RELATIVE_ABUNDANCE_CONTIGS........................ 688          0.082%
PORTION_COVERED_CONTIGS........................... 685          0.082%
ABUNDANCE_SPLITS.................................. 683          0.082%
MEAN_COVERAGE_SPLITS.............................. 683          0.082%
NORMALIZED_COVERAGE_SPLITS........................ 683          0.082%
STD_COVERAGE_SPLITS............................... 683          0.082%
RELATIVE_ABUNDANCE_SPLITS......................... 682          0.082%
PORTION_COVERED_SPLITS............................ 668          0.080%
MAX_NORMALIZED_RATIO_CONTIGS...................... 649          0.078%
MAX_NORMALIZED_RATIO_SPLITS....................... 647          0.077%
VARIABILITY_CONTIGS............................... 465          0.056%
VARIABILITY_SPLITS................................ 453          0.054%
COLLECTIONS_OF_SPLITS............................. 344          0.041%
STATES............................................ 117          0.014%
SQLITE_MASTER..................................... 8            0.0%
COLLECTIONS_COLORS................................ 1            0.0%
COLLECTIONS_INFO.................................. 1            0.0%
COLLECTIONS_OF_CONTIGS............................ 1            0.0%
SELF.............................................. 1            0.0%
VIEWS............................................. 1            0.0%
~~~

Newly added SPLIT_COVERAGE_VALUES table is the most of the database.

This is not manageable.

Because all coverage values are simple arrays, I am planning to switch to HDF5 to store them on disk and for fast access to these values.

I am sorry this is taking longer, and our trunk is currently in an unstable state. I should have done all these in a branch :( I apologize for my sloppiness. I thought this would have been much more straightforward.

**Comment by meren** [comment]
I think we are almost there.

There is no longer a `anvi-script-upgrade-profile-db-v6-to-v7` script, because the profile database is back to version 6.

To upgrade current analyses we have a new converter, `anvi-script-generate-auxiliary-data-from-summary-cp`, which takes a SUMMARY.cp and a profile db, and creates a `AUXILIARY-DATA.h5` file.

I will close this and make a new release after some heavy testing during the weekend.

**Comment by amaralzettler** [comment]
Hi Meren,

Please let me know when it is safe to update.

Thanks!

Linda

P.s. Did you ever speak to Rich about the CONCOCT issue?

From:  "A. Murat Eren" <notifications@github.com>
Reply-To:  meren/anvio
<reply+00c4d5f1bff14b870ea4c0e209dc01a093c486e68aaa8bf392cf000000011214612d9
2a169ce06610d07@reply.github.com>
Date:  Friday, September 18, 2015 at 7:33 PM
To:  meren/anvio <anvio@noreply.github.com>
Subject:  Re: [anvio] Killing the SUMMARY.cp (with fire .. and HDF5). (#202)


I think we are almost there.

There is no longer a anvi-script-upgrade-profile-db-v6-to-v7 script, because
the profile database is back to version 6.

To upgrade current analyses we have a new converter,
anvi-script-generate-auxiliary-data-from-summary-cp, which takes a
SUMMARY.cp and a profile db, and creates a AUXILIARY-DATA.h5 file.

I will close this and make a new release after some heavy testing during the
weekend.


Reply to this email directly or view it on GitHub
<https://github.com/meren/anvio/issues/202#issuecomment-141593732> .

**Comment by meren** [comment]
Hi Linda,

Please always stick with the latest stable release from [releases](https://github.com/meren/anvio/releases). If you are watching the repository you must be getting e-mails whenever there is one :)

I haven't talked to Rich about the CONCOCT issue, and I don't think I will have time for that :( You should show him the error you are getting, and maybe he can think of a way to fix it.

Thank you,

**Comment by amaralzettler** [comment]
Thanks meren  I¹ll do that.  For the record, no one at the JBPC (perhaps
other than yourself?) seems to have successfully run CONCOCT ­ but Jeff
Bowman (at Lamont) has so I am going to follow up with him.

I hope you are feeling better :).

L

From:  "A. Murat Eren" <notifications@github.com>
Reply-To:  meren/anvio
<reply+00c4d5f1027e1094e7cad98ea4c44f329e74493377b2050192cf000000011214fc7b9
2a169ce06610d07@reply.github.com>
Date:  Saturday, September 19, 2015 at 6:35 AM
To:  meren/anvio <anvio@noreply.github.com>
Cc:  Linda Amaral Zettler <amaral@mbl.edu>
Subject:  Re: [anvio] Killing the SUMMARY.cp (with fire .. and HDF5). (#202)


Hi Linda,

Please always stick with the latest stable release from releases
<https://github.com/meren/anvio/releases> . If you are watching the
repository you must be getting e-mails whenever there is one :)

I haven't talked to Rich about the CONCOCT issue, and I don't think I will
have time for that :( You should show him the error you are getting, and
maybe he can think of a way to fix it.

Thank you,


Reply to this email directly or view it on GitHub
<https://github.com/meren/anvio/issues/202#issuecomment-141643749> .
