### ISSUE TITLE
Install problems (again)

### ISSUE THREAD

**Issue by drjcthrash** [meren/anvio#209]
Hello,
I'm sorry to trouble you again, but after returning to work with Anvi'o today, the previous installation is not letting me complete tasks any longer.

As of our last outing, you had me complete the following:

``` bash
cd /tmp
git clone -b v1.2.0  --depth=1 https://github.com/meren/anvio.git
cd anvio/tests
./run_mini_test
```

When I looked in /tmp today, anvio was no longer there, so I re-installed it in this way, but received the following output 

``` bash
$ ./run_mini_test.sh 

#
#
# Creating the output directory ...
#
#


#
#
# Anvo'o version ...
#
#

./run_mini_test.sh: line 12: anvi-profile: command not found
```

It doesn't work with sudo either.

I removed the /tmp/anvio directory and attempted to install in /usr/local/bin, where I usually put tools of this nature.

``` bash
$ sudo pip install anvio
The directory '/Users/JCThrash/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/JCThrash/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): anvio in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): bottle>=0.12.7 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from anvio)
Requirement already satisfied (use --upgrade to upgrade): pysam>=0.8.3 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from anvio)
Requirement already satisfied (use --upgrade to upgrade): hcluster>=0.2.0 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from anvio)
Requirement already satisfied (use --upgrade to upgrade): ete2>=2.2 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from anvio)
Requirement already satisfied (use --upgrade to upgrade): scipy in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from anvio)
Requirement already satisfied (use --upgrade to upgrade): scikit-learn>=0.15 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from anvio)
Requirement already satisfied (use --upgrade to upgrade): django>=1.7 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from anvio)
Requirement already satisfied (use --upgrade to upgrade): cython>=0.21a1 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from anvio)
Requirement already satisfied (use --upgrade to upgrade): h5py>=2.5.0 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from anvio)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.6.1 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from h5py>=2.5.0->anvio)
Requirement already satisfied (use --upgrade to upgrade): six in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from h5py>=2.5.0->anvil)
```

This appears to indicate I have everything installed, but I don't know what directory it is in. There is no anvio directory in /usr/local/bin, nor in /opt/local/bin where macports has been putting everything.

Can you help me get back on track?

Thank you.

**Comment by meren** [comment]
Hi Cameron,

I am sorry for confusing you. What we did under the /tmp directory was simply to run mini_test. So you had anvi'o installed, and then downloaded a copy of the codebase in there just to run the mini_test with your installed anvi'o. It is OK for everything under the /tmp to be gone.

Your installation is still there, too. It is again the PATH problem we are facing here. When you type any anvio program your terminal tells you it is not there, because your PATH does not include the directory where your Python binaries reside.

Please paste these lines into your terminal:

``` bash
echo 'export PATH=$PATH:/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin' >> ~/.bashrc
source ~/.bashrc
```

Then everything will magically work (including the mini_test).

If you run into similar issues, please send me a direct e-mail, if we identify a problem we can open an issue to get them fixed :)

I hope anvi'o would prove useful to you after all these trouble it caused you.


Best,

**Comment by drjcthrash** [comment]
Hi Murat,
Ok, thanks. I’ve done this. Where is the anvio directory now? Having done the pip install, I’m not sure where to find it...

-jct
