### ISSUE TITLE
Where does a scaffold go if it contains a highly conserved gene?

### ISSUE THREAD

**Issue by fuhrmanlab** [meren/anvio#210]
Hello,
If there is a scaffold that has a conserved gene, meaning it is genetically similar between all organisms of a given taxa, how does it get sorted?  Does it go with one bin only, such that it is now missing from all other bins of related taxa?
Thanks,
Alma

**Comment by meren** [comment]
Hi Alma,

I'd say it really depends on the assembler and the coverage of the scaffold. Depending on the combination of factors it may get assembled in one scaffold and would recruit all reads coming from other genomes, or it may end up as a short contig, breaking up the flanking parts of the scaffold that contains the gene into multiple pieces.

I invite @tdelmont to comment on this as well.


Best wishes,

**Comment by tdelmont** [comment]
Hi Alma, good question!
As Meren mentioned, this is an assembly issue. Anvi'o does not attempt to improve assemblies so far. If a gene is identical between populations (but not the rest of their genomes), then it will end up in one bin only (with unusually high coverage value) or will become a very short scaffold (generally not used for the binning).

However, I want to add a comment that I think is relevant to this discussion. In my experience, when one gene is almost identical between two populations (let's not think about mobile genetic elements here), then the rest of the two genomes are highly identical as well. Then, genomes from the 2 populations will be co-assembled into a single bin. At this stage, only single nucleotide variations (a close concept to SNPs) can separate the 2 genomes. While anvi’o provides this information, so far it does not offer the capability to “deconvolute” co-assembled genomic populations. But people are working on this!

Best, 
Tom.
