### ISSUE TITLE
Default state for anvi-interactive

### ISSUE THREAD

**Issue by meren** [meren/anvio#211]
There must be an option to load a default state while calling `anvi-interactive`.

If it is not there, it shouldn't load anything, if it is there, it should load the state *and* call draw immediately (since there is a state, the user will unlikely change anything before clicking 'draw', so let's do it as well).

Best,

**Comment by meren** [comment]
This is awesome, Ozcan. However, there is one thing I would like us to do something about. Here is what I do:

* run mini test
* click draw
* save the state as "test"
* close tab. kill server. 
* `cd sandbox/test-output/204-MERGED`
* `anvi-interactive -p PROFILE.db -c ../CONTIGS.db --state test`

this results in this error:

![image](https://cloud.githubusercontent.com/assets/197307/10798088/d7823b88-7d73-11e5-9872-82f683a57f1a.png)

the reason to that is because the initial run where the state was saved was run with this command:

    `anvi-interactive -p PROFILE.db -c ../CONTIGS.db --state test --split-hmm-layers`

where `--split-hmm-layers` changes the number of layers.

One way to deal with this could be a more flexible way of matching state info to available layers. Alternatively, we can check whether state is compatible with available layers, and show a small info on the top right saying "the state is not compatible with the current layers", and fall back to the default plan (as of `--state` has not been used).

What do you think?

**Comment by ozcanesen** [comment]
Hey Meren,
Load state function already works like that, so number of layers does not really matter. Load state function skips extra layers in state file also uses default values for missing layers.

I followed the steps but could not reproduce the problem, here is a screencast:  https://www.youtube.com/watch?v=WOojJKIK_aY

**Comment by meren** [comment]
This is very weird.....

I did the exact same thing, and had the same problem again. What software did you use for that screencast?

So I can do the same and show it to you :)

**Comment by ozcanesen** [comment]
I have used built in quicktime for screencast.

Can you send me test-output directory maybe i can reproduce the error that way?

**Comment by meren** [comment]
Thanks for looking into this Ozcan :/ The test directory is attached.

When I simply run it like this:

    anvi-interactive -p PROFILE.db -c CONTIGS.db

And load the `test` state, it crashes. But if I run it like this, the `test` state loads.

    anvi-interactive -p PROFILE.db -c CONTIGS.db --split-hmm

PS: Clearly the newly added parameter `--state` works beautifully, and this seems to be another glitch...

**Comment by meren** [comment]
"attached".

Lies...

Here:

https://www.dropbox.com/s/j6sibe242aoefqf/204-MERGED.tar

**Comment by ozcanesen** [comment]
Hey Meren, can you try again?

btw this code part overwrites state variables, i think they should only modify default values not the state. what do you think about it?
<img width="541" alt="screen shot 2015-10-31 at 12 52 59 am" src="https://cloud.githubusercontent.com/assets/940884/10859009/ee3ec1ee-7f61-11e5-9d21-db63644c3fc1.png">

**Comment by meren** [comment]
Awesome, Ozcan! 217146ba1113a210c7d02001cebe672ce8c49352 resolves this completely.

And you are correct, those ad-hoc stuff only modify default values, and not the state. If you don't want to fix that I can correct this.

Thank you!
