### ISSUE TITLE
run_mini_test fail

### ISSUE THREAD

**Issue by shenwei356** [meren/anvio#212]
All dependencies except MyRAST are installed. And Chrome is default browser, the test `python -c 'import webbrowser as w; w.open_new("http://")'` passed.

But running test did not work.

```
git clone -b v1.2.0 --depth=1 https://github.com/meren/anvio.git
cd anvio/tests
./run_mini_test.sh
```

Here is the last rows of the output:

```

#
#
# Contigs DB is ready; here are the tables in it:
#
#

SQLite header and source version mismatch
2013-05-20 00:56:22 118a3b35693b134d56ebd780123b7fd6f1497668
2015-07-29 20:00:57 cf538e2783e468bbc25e7cb2a9ee64d3e0e80b2f
```

Browser did not popup.

**Comment by meren** [comment]
Hi Wei,

A Google search on that error returns a lot of pages. I suggest you to search the error message on Google by including the operating system you are using in the search box (this is not an anvi'o issue).

Best wishes,

**Comment by shenwei356** [comment]
Thank you meren, it's my negligence.
