### ISSUE TITLE
anvi-populate-genes-table error

### ISSUE THREAD

**Issue by jgabriel1206** [meren/anvio#214]
Hi Meren

I got this error when I tried to run anvi-populate-genes-table:

File/Path Error: Not all lines in the file 'svr_assign_to_dna_using_figfams.txt' have equal
                 number of fields...

I tried to fix this problem by using a simple awk command to replace spaces for _ in column 4, assuming that this was the issue:

awk '{x=$4; gsub(/ /,"_",x); print $1,$2,$3,x,$5}' svr_assign_to_dna_using_figfams.txt > svr_assign_to_dna_using_figfams_awk.txt

I tried to run the program again using the modified file but I got this new error:

Config Error: Mapping funciton '<type 'int'>' did not like the value '' in column number 2 of
              the matrix :/

Do you know why am I getting this error?
Thanks 
Gabriel

**Comment by meren** [comment]
Hi Gabriel,

Can you go back to the original file and run this please:

``` bash
awk 'BEGIN{FS="\t"}{print NF}' svr_assign_to_dna_using_figfams.txt | sort -n | uniq -c | sort -nr
```

Best,

**Comment by jgabriel1206** [comment]
Hi Meren

I used the awk command and got this:

awk 'BEGIN{FS="\t"}{print NF}' svr_assign_to_dna_using_figfams.txt | sort -n | uniq -c | sort -nr 
772683 5
          1 1
Then I tried again with anvi-populate-genes-table, but I got the same error:

File/Path Error: Not all lines in the file 'svr_assign_to_dna_using_figfams.txt' have equal
                 number of fields...

Thanks
Gabriel

**Comment by meren** [comment]
Hi Gabriel,

According to the output you have 772,683 lines in that file with 5 TAB-delimited fields, and 1 line with only  1 TAB-delimited field. The error is accurate, and you need to remove that line, things will work out nicely.

Hint: It could be an extra line at the VERY end of the file. I can help you remove that if you send me the compressed file via e-mail (a.murat.eren at gmail).

Best wishes,
