### ISSUE TITLE
Layer labels are missing from the SVG output (in Inkscape)

### ISSUE THREAD

**Issue by meren** [meren/anvio#216]
This is what happens when you run the `mini-test`, draw the tree, and click the save button¹, and open the resulting SVG file in Inkscape:

![image](https://cloud.githubusercontent.com/assets/197307/10793161/ab7fa360-7d5d-11e5-8906-0646df4dc2a1.png)

Although, the same file looks like this in Safari:

![image](https://cloud.githubusercontent.com/assets/197307/10793207/cf1b8a1e-7d5d-11e5-81d5-2543c53eeba1.png)

(Also, the serif fonts are not really good to put in these SVG outputs, it would have been great if the saved SVG was identical to the SVG displayed on the interactive interface).

¹ it is this one on the left:

![image](https://cloud.githubusercontent.com/assets/197307/10793050/3c26c836-7d5d-11e5-894d-53419a61bcbf.png)

**Comment by ozcanesen** [comment]
Hey Meren, is your repo updated? because i have fixed this bug and few other inkscape related bugs a week ago.
<img width="1054" alt="screen shot 2015-10-28 at 7 26 22 pm" src="https://cloud.githubusercontent.com/assets/940884/10795252/9ba7237a-7da1-11e5-9386-b7507aa66fd8.png">

**Comment by meren** [comment]
if that's the case I will shoot myself with a very big bullet.

I will write back in an hour. Thank you!

**Comment by meren** [comment]
I confirm :/ This is an invalid report. I don't know how I missed that. 

Thank you very much, Ozcan.
