### ISSUE TITLE
Tree parsing issue in samples.js

### ISSUE THREAD

**Issue by meren** [meren/anvio#217]
OK. I spent quite a bit of time to figure this out, and I surrender.

Here is the dataset to reproduce the issue:

https://www.dropbox.com/s/09ej86k9a1mde2h/issue.tar

after downloading this, this is how to reproduce (after a fresh `git pull`):

``` bash
tar -xvf issue.tar
cd issue
./run.sh
# click 'Samples' tab,
# select 'phylogeny (tree)' from the "sample order" combo,
# click Draw
```

Which results in the following:

![image](https://cloud.githubusercontent.com/assets/197307/10860148/bae78cd8-7f32-11e5-8c35-6487b8109eee.png)

The newick seems to be OK. I am not sure what is happening here :/ Whatever it is, we need to find a way to check for it :(

Meanwhile I will just crumble here into a small pile of dust.

Thanks a lot in advance.

**Comment by ozcanesen** [comment]
I checked newick and root node has 3 child, I think that causes the problem here.

<img width="451" alt="screen shot 2015-10-31 at 3 17 45 am" src="https://cloud.githubusercontent.com/assets/940884/10860747/bb151020-7f75-11e5-9d76-1637a9e3d07f.png">

**Comment by meren** [comment]
So it is a legal tree but we can't handle it? That's OK. We don't have to. We would just need to be able to communicate that the tree is beyond what we support (which doesn't sound so nice, but would be sufficient until we have the energy to do something real about it).

**Comment by ozcanesen** [comment]
Yes it is absolutely legal tree and actually we can handle it and we have to, but i hardcoded it and don't know how to fix it.
This line causes the problem i am going to work this https://github.com/meren/anvio/blob/master/anvio/data/interactive/js/sample.js#L605

**Comment by ozcanesen** [comment]
No i was wrong (3 child nodes is OK) the problem is layer 'WCFS1' does not exists on the main tree.

<img width="302" alt="screen shot 2015-10-31 at 3 53 06 am" src="https://cloud.githubusercontent.com/assets/940884/10860977/8c8d5e60-7f7a-11e5-936d-c441aecc3d7d.png">
<img width="385" alt="screen shot 2015-10-31 at 3 45 35 am" src="https://cloud.githubusercontent.com/assets/940884/10860984/abec0fc2-7f7a-11e5-8db0-1367a6aa1e24.png">
<img width="498" alt="screen shot 2015-10-31 at 3 55 17 am" src="https://cloud.githubusercontent.com/assets/940884/10860991/dab006f6-7f7a-11e5-96e0-6731b0362e49.png">

**Comment by meren** [comment]
OK. Great. It is my fault, then. The problem is, when we are in the manual mode, it is very hard to make sure samples in the tree and view matches.

Thank you very much for looking into this :(

I will find a way to make sure the incoming data is legit.. Meanwhile, can we show an error for it in the interface for the sake of handling it?

I owe you a beer. Or a non-diet coke :)

**Comment by tdelmont** [comment]
I gave the tree to Meren, so I am definitely the one to owe you a six-pack!
Thanks Ozcan for all your hard work and keeping interest in the project.
Greatly appreciated.

**Comment by ozcanesen** [comment]
Thanks for all the beers :) I have added the error message.
