### ISSUE TITLE
Label for the bar data structure

### ISSUE THREAD

**Issue by meren** [meren/anvio#222]
Hi,

Here is the problem in the samples information section in the tree:

![image](https://cloud.githubusercontent.com/assets/197307/11022034/05a76296-861a-11e5-960b-5bd21ab36b38.png)

and the section in the legends:

![image](https://cloud.githubusercontent.com/assets/197307/11022041/5d88101e-861a-11e5-9309-aa62dc890a80.png)

As you can imagine, when there are like 30 items in the bars data structure, these labels get very long and becomes quite ugly :) I have a suggestion!

Currently we expect the header field for the bar data structure to look like this:

    bar1;bar2;bar3
    2;4;6
    3;5;7

How about we require this format instead:

    foo!bar1;bar2;bar3
    2;4;6
    3;5;7

This way we would know that this is a bar data structure with three dimensions, and the label is "foo".

Best,

**Comment by ozcanesen** [comment]
Hey Meren,
This sounds very logical and i think i can implement this backward compatible.

**Comment by meren** [comment]
Hi Ozcan!

Thank you for looking into this. I saw your commit and had a chance to test it today with an up-to-date repository. I am running run_manual_interactive.sh with a newly gnerated samples database, and this is what I get:

![image](https://cloud.githubusercontent.com/assets/197307/11149942/de60a056-89ea-11e5-97ee-fdb7c62076bb.png)

And the legend looks like this:

![image](https://cloud.githubusercontent.com/assets/197307/11150026/4f3ca7fc-89eb-11e5-8699-4642652f2427.png)

I'm curious whether it's the same when you run it.


Ciao!

**Comment by ozcanesen** [comment]
Hi Meren,
It does only work for the main tree at the moment, i will commit samples layer changes today.
Best,

**Comment by meren** [comment]
Understood! :) Thank you very much again.
