### ISSUE TITLE
summary redundancy when refining 

### ISSUE THREAD

**Issue by tdelmont** [meren/anvio#228]
Hi, I realize summary is taking a lot of time when refining bins from large bin collections.
Every time we work on refining some bins, we need to re-do the summary of all bins (most of them are unchanged...) to integrate changes.
This is time consuming, and very redundant.
Any chance we can improve this?

Tom

**Comment by meren** [comment]
Doing an incremental summary is not an option at the moment. But I added a new flag, `--quick-summary`, to ameliorate the performance issues (a538187c1ddba70267bc5527a42bf97da8261d64).

Good suggestion, Tom. Thank you.
