### ISSUE TITLE
Import functional annotation from RASTtk

### ISSUE THREAD

**Issue by mdehollander** [meren/anvio#238]
Hi,

I had some issues in running `svr_assign_to_dna_using_figfams` from MyRAST (no output produced), so I looked at current alternatives. Also the data I use mainly comes from soil, so being able to use alternative resources would be nice.
The recent updated RASTtk scripts can be a nice alternative, although `anvi-populate-genes-table` does not have a parser for it. The output can be in JSON/GTO format (http://www.nature.com/articles/srep08365), or it can be exported to GFF (http://tutorial.theseed.org/RASTtk/RASTtk_Incremental_Commands.html). Any advice for using alternative for MyRAST like RASTtk?

Thanks

**Comment by meren** [comment]
Hi!

Thank you very much for the suggestion. We are changing the way we were handling gene calls and functional annotation completely, so I will suggest a workaround so if you like, you can use RASTtk output from within anvi'o. 

`anvi-populate-genes-table` also accepts simple matrix files. There is an example for it in the [tests/run_all_tests.sh](https://github.com/meren/anvio/blob/v1-branch/tests/run_all_tests.sh) file that may be helpful to understand the format:

``` bash
INFO "Re-populating the genes tables in the contigs database using the recovered matrix file with 'default_matrix' parser ..."
anvi-populate-genes-table -c test-output/CONTIGS.db -p default_matrix -i test-output/functions_and_taxonomy_sample_matrix.txt
```

If you execute `run_all_tests.sh` in the `tests/` directory for once, you can use the `functions_and_taxonomy_sample_matrix.txt` file in `tests/sandbox/test-output/` directory to mimic what the simple matrix should look like.


Best,

**Comment by mdehollander** [comment]
Thanks for pointing to the matrix import, that would work for now. I had to clone the v1-branch to get the tests working, since the test is not included in the master branch.

It would also be nice to import classifications from UProC (http://uproc.gobics.de/), since this tool can screen HMMs from KEGG and PFAM against contigs very fast. I will also look into this.

**Comment by meren** [comment]
Thank you very much for suggesting UProC. It really looks like something that will be very useful to incorporate into 2.0 clade. Currently I am testing InterProScan, and I am very happy with the results.

But UProC can definitely be an option. I will close this one, and start a new issue as a reminder.

Best wishes,
