### ISSUE TITLE
User management/admin interface

### ISSUE THREAD

**Issue by meren** [meren/anvio#243]
A feature that will be more and more needed :)

**Comment by paczian** [comment]
I'll get right on it

**Comment by meren** [comment]
Thank you, Tobi!

Please don't hesitate to commit directly to master. You have full access to the repository.

**Comment by paczian** [comment]
The initial version of this is done. I need to add searching and filtering as well as list number of projects.

**Comment by paczian** [comment]
Added filtering, sorting and browsing as well as number of projects to the user table.
