### ISSUE TITLE
accepting samples-organization and samples-order files in new projects

### ISSUE THREAD

**Issue by meren** [meren/anvio#254]
I think we should accept samples-organization and samples-order files in this window to provide access to a larger functionality of the interactive interface:

![image](https://cloud.githubusercontent.com/assets/197307/12096263/ae9dbe86-b2d9-11e5-9eba-fb6bd955c020.png)

There are example files for both in `tests/sandbox/files_for_manual_interactive`. Making use of these files is a bit tricky, because if the user provides either or both of them, we need to create a samples database from them first in the project directory. But once the files are available, it is as easy as these two lines of code to create a samples database:

``` python
s = dbops.SamplesInformationDatabase('/.../user/project/SAMPLES.db', run, progress, quiet=True)
s.create(samples_information_file_path, samples_order_file_path)
```

Thanks! :)

**Comment by paczian** [comment]
addressed in #259 
I tried this with the test files and it did not break, but I did not notice any difference in the output. What should this look like?

**Comment by meren** [comment]
Hey Tobi, 

I found another bug somewhere else in the code that will have to be fixed for this to work. I will take care of this one along with the other issue.

**Comment by meren** [comment]
this depends on #261.

**Comment by meren** [comment]
This is done! Thank you, Tobi :)
