### ISSUE TITLE
"Share project" issue

### ISSUE THREAD

**Issue by meren** [meren/anvio#255]
To test the "share project" functionality I sent two commits (cdc48db644753f7e667e22bcf75039958ce9a6b4 and d01cce16f3d297fd5b356eacf3565171b7bfde45), and now I can click share without getting any unexpected error. But this time I get another one, so I thought I should report this as a new issue :) Sorry for the SPAM.

This is what I did; run `./run_server_test.sh mock`, login as `meren` / `test`, click share project for m_proj_01, type in a name:

![image](https://cloud.githubusercontent.com/assets/197307/12100307/cab93360-b2f3-11e5-85a7-1e7689b8973b.png)

When you click share button, this shows up:

![image](https://cloud.githubusercontent.com/assets/197307/12100268/8c59e2e0-b2f3-11e5-85d5-ec8e68b7d5a8.png)

If you try to share again with the same name, you get this written on the side of the project page:

```
share project failed
view name already taken
```

If you do it *again* with a different name, this time this gets printed on the side of the project page:

```
share project failed
The user does not own this project
```

So there is a lot going on there :)

**Comment by paczian** [comment]
fixed in #259
