### ISSUE TITLE
anvi-server design results in multiple calls for `InputHandler`

### ISSUE THREAD

**Issue by meren** [meren/anvio#257]
Hi @paczian,

I randomly put a print statement to see how many times the InputHandler was being called (line 715):

![image](https://cloud.githubusercontent.com/assets/197307/12100594/a15d37e4-b2f5-11e5-8c26-56c51782ac93.png)

Then I did `./run_server_test.sh mock`, logged in as `meren` / `test`, and clicked on m_proj_01 to view it, and there were multiple calls:

![image](https://cloud.githubusercontent.com/assets/197307/12100545/40106362-b2f5-11e5-87a4-abd00077d25d.png)

What causes this is the `set_user_data` function calls from within the `bin/anvi-server` file.

This design was fine with `anvi-interactive`, because the object `d` was always in memory and we had only one user to deal with. When we started implementing a stand-alone server, of course `d` was not static, and needed to be re-generated for each call based on the `login`. So I understand the need, but we have to think something smart for this without breaking other things. In the best case scenario, we would have one call to InputHandler class.

I think it's worth thinking on this a bit :)

**Comment by paczian** [comment]
I think I can reduce that a lot by making a resource for the init call that returns the initial data in bulk.

**Comment by paczian** [comment]
I have added a bulk init call and enabled that in main.js, but this will require anvi-* scripts other than anvi-server to respond to the /data/init resource as well. It is just a couple of lines of code that needs added and it would also allow to configure whether you want the timed server ping or not.

Other than anvi-interactive I do not know which scripts start a bottle server. All of those would need to be updated, hence I did not send a pull request yet.

**Comment by meren** [comment]
> Other than anvi-interactive I do not know which scripts start a bottle server

anvi-interactive and anvi-refine :)

**Comment by meren** [comment]
You can run `./run_all_tests.sh` script to see whether there are some outstanding issues with them after the change.

Thanks!

**Comment by paczian** [comment]
addressed in #262 
I cannot run the all tests thing because of my concoct issue, but I tested the run_mini_test_wo_concoct and it worked. This reduces the number of initializations to 3 (down from 16) which is not perfect, but better. This also addresses the issue of having an option to turn the server ping on and off (I turned it off in anvi-server and on in anvi-interactive and anvi-refine)

**Comment by meren** [comment]
The code seemed alright to me, and I will check this now to make sure everything works :)

**Comment by meren** [comment]
OK, I was wrong :) There were many little bugs in anvi-refine (44cc6e6572596ce772c71c7ce44863aa7554c9bd). I have to leave now so I couldn't check, but I am sure they are also present in anvi-server.

This tells me that that function (`send_data` in anvi-refine and anvi-interactive) has to be re-designed so there is no redundancy, and hence less room for error. I will look at that in a separate issue.

**Comment by meren** [comment]
Nevermind what I said! There were no bugs in anvi-server :)

**Comment by meren** [comment]
I say going down from 16 to 3 is a significant improvement. If we run into issues later, we can reopen this.
