### ISSUE TITLE
share project URLs

### ISSUE THREAD

**Issue by meren** [meren/anvio#264]
Hi Tobi,

Here is an example URL for a shared project with name `test_share` with the current codebase:

    http://localhost:8080/project?name=test_share

I think this would be a better URL for this:

    http://localhost:8080/public/meren/test_share

 This way the same name can be used for multiple projects, and the URL would look a bit more human-friendly. What do you think? Is this too hard to achieve?

Best,

**Comment by paczian** [comment]
the task was hard
but the outcome was useful
now it is done

addressed in haiku #267 ;)

**Comment by meren** [comment]
You are the best! :) Thank you again! We made lots of progress.
