### ISSUE TITLE
New fields for the database

### ISSUE THREAD

**Issue by meren** [meren/anvio#265]
Hello (me again),

I have some suggestions for the database.

* I think we should keep track of the last login date, and the number of projects per user, so users can be sorted based on this information in the admin panel.
* For each project we should have the number of samples, and number of leafs (and any other relevant information) stored in the database.

Best,

**Comment by paczian** [comment]
The number of projects is already in the admin table. The metadata for the project is something we should keep track of and that would help to offer the user a better understanding of their data. This could be displayed on the users projects page.
I will add the last login field to the user db.

**Comment by meren** [comment]
Thank you, Tobi! Yet another suggestion while we are on this topic:

If there was a table underneath this called "Projects Table", where every project is listed with a field of login name, and all other metadata regarding each project, it would have been very useful to manage most things in the users database:

![image](https://cloud.githubusercontent.com/assets/197307/12146086/6882d45c-b457-11e5-8478-0d4ab7ec5801.png)

Finally, if both tables had "delete" buttons both for projects and users, than the master Paczian would have the power to truly rule the world of his minions :)

2 cents.

**Comment by meren** [comment]
I just can't stop, I know :( This just occurred to me:

I also think there should be an option to add some description for each project. Like an optional textarea in the "new project" window, and then ability to edit the contents through settings. We can show a fancy popup for it in the interface if description is not empty. This will be very helpful for people to describe what this project is all about beyond a single word "project name".

**Comment by paczian** [comment]
this has been partially addressed in #269
I do still need to add the user delete function. This requires care (as lots of data may be destroyed) and some cleanup, so the directory is removed and all database entries regarding that user are purged. I will add a delete function for users in the backend.
The users projects are available through the impersonation button (including the option to delete them). I will probably add a project table on the admin page anyway so the data is searchable.
I have added a metadata table that associates key value pairs to a project. These data will then be displayed in the project settings popup. Now I just need to know what data we want and how I can get it so I can add it to the db.

**Comment by meren** [comment]
I guess we want to show how many leaves in the tree, and how many layers in all files. I guess I should make that information available through interactive.py with a bottle callback to return that, so it can be stored in the database upon the creation of the project.

**Comment by paczian** [comment]
I have added a project table to the admin page. You can also view the details of each project, including all its files. I got caught up in pixel pushing, so the delete functions still need to be added. I will get to that on monday. I will also add functions to replace the project files for both the admin page and the user project page.

**Comment by meren** [comment]
Thanks! :)
