### ISSUE TITLE
The mighty "text layer"

### ISSUE THREAD

**Issue by meren** [meren/anvio#288]
Hi @ozcanesen,

Thank you for taking a stab at this :)

I just uploaded a new [file](https://github.com/meren/anvio/commit/1b17a046842bae2e220493f906e638fe1f4e4321) to make it easier to test some of the work you are doing via `./run_manual_interactive.sh` script.

I thought we can have an issue to list ideas and discuss solutions regarding this new addition. I have a couple of very quick suggestions:

* When a categorical layer contains more than 12 different categories, I think it is safe to set the default type "text". Otherwise the interface generates a crazy number color boxes in the legend section, and it slows down everything.

* As an idea: in theory text layers can have a background and foreground color, and I am curious whether we can add it when the text is selected in the combo like the way we do in the intensity.

![image](https://cloud.githubusercontent.com/assets/197307/12526215/b17192f8-c130-11e5-8ad3-0b609373e397.png)

* For layers of "text" type, we can remove color boxes from the legend to improve performance?

Thank you very much for looking into this! :)

**Comment by ozcanesen** [comment]
Hey Meren,

The ideas that you suggested are implemented, can you test it and give me feedback and maybe new ideas?

Best,
Özcan

**Comment by meren** [comment]
Hey Ozcan,

I just tested these changes, everything looks awesome!

I have an ignorant suggestion, and I would like you to tell me if it is not feasible: The height of the layer could be automatically computed based on the longest word in the list, and when the text layer is moved from one place to another, the default height would have been computed again (because, for instance, a height of 100 does not mean the same as the most inner layer, and most outer layer). The user can of course change it, but we would put a default that takes into consideration the longest item in the list whenever possible :)

By the way I was looking at open fonts, Inconsolata seems pretty awesome as a monospace font.


Thank you very much again!

**Comment by meren** [comment]
Thinking about it more... Maybe the height of the text layer should also define the text size. Because when we calculate the text size based on the angle alone, this is what happens with a small tree (I simply removed everything but the first 50 entries in tests/sandbox/files_for_manual_interactive):

![image](https://cloud.githubusercontent.com/assets/197307/12572603/279a41b6-c3b4-11e5-8b3f-8231a4a3143f.png)

In this case if you want to see everything, you have to make the text layer height like 5000.

So, I guess calculating the height of the layer automatically is not the best idea. I guess we should calculate the font size based on the layer height (but it should never go beyond the maximum font size the angle can support before words start overlapping on each other).

2 cents.

**Comment by ozcanesen** [comment]
Hey Meren,

Can you test again?
- There is no height input box for text layer type, it is all automatic
- We calculate font size, for small inner layers it is required, but there is a maximum value which is 18px, you can tweak it if you want.
- By the way we should not use custom web fonts because probably Inkscape will not show them.

Best,
Özcan

**Comment by meren** [comment]
Hey Ozcan,

Great!

I think you are correct. We shouldn't use custom fonts to maintain compatibility. If everything in the text layer are grouped together in the SVG output, people can change the font quickly if they want.

I really like the fact that there is no height for the text-type layer. Very creative. Meanwhile I think the ability to parameterize that `18` here would be a great addition to the functionality of the interface (and to store it in/read it from the state, of course):

``` python
var layer_font = Math.min((layer_perimeter / leaf_count), '18');
```

One final minor suggestion. Do you see how the text starts exactly starts at where the background starts (and ends at exactly where background ends for the longest item):

![image](https://cloud.githubusercontent.com/assets/197307/12626727/bd6cc1cc-c4ff-11e5-8f50-b87e8871de44.png)

These are little things, but affect the perception a lot. It would have been great if we had some room for the start and end. I know how challenging it is to do these things over ratios, but maybe we can say "there will always a one-character long distance between where the background starts and where the text starts". What do you think? You can tell me to stop being so detail oriented and I would :p

Thanks a lot!

**Comment by meren** [comment]
(funny, I can see the relevant commit to show the `max-font-size-input` (https://github.com/meren/anvio/commit/fe1fc543af5f815bd86110f9e581e951e1756580), but it doesn't show my up-to-date interface from text-layers branch).

**Comment by ozcanesen** [comment]
Hey Meren,

It is hidden by default, it will be visible if there is at least one categorical layer with more than 12 unique items or after you manually select "text" as a type, I did it this way because i wanted to keep user interface clean ( i know it is too late for this :) ) i can change it if you think it is confusing, but i think showing something saying "Font Size" is more confusing because users will not see any difference if they change it unless there is a text layer.

By the way, i think this branch is stable enough and we can merge it after last checks, it works for phylogram too, but no hope samples yet.

Best,

**Comment by meren** [comment]
I think it is very smart to keep it hidden by default, and I like that design. But even when a layer is a proper text layer, I can't see any `max-font-size` box:

![image](https://cloud.githubusercontent.com/assets/197307/12658968/c0c24d74-c5d1-11e5-89c1-83a084feffd0.png)

:)

**Comment by meren** [comment]
& I agree! the branch is stable enough to merge into master.

**Comment by ozcanesen** [comment]
Hey Meren
Can you run $('.max-font-size-input').show(); on console, i have no clue why it is hidden on you :S

**Comment by meren** [comment]
Ozcan :((( It is hidden to me because I am not a very smart man :(

It works beautifully. Sorry about the confusion.

**Comment by meren** [comment]
I am closing this. Everything seems to be working for now :)

You are a hero, Ozcan. Thank you.
