### ISSUE TITLE
Anvio-server - failed to process a project

### ISSUE THREAD

**Issue by tdelmont** [meren/anvio#291]
Hi,
on my first test with the anvio-server, the project I created failed to load on the interactive interface. 
Here is the error code:

![screen shot 2016-01-27 at 10 07 18 am](https://cloud.githubusercontent.com/assets/8332889/12619517/fe0640d6-c4dd-11e5-9a11-7b7a1b5ef832.png)

PS: my id is "tdelmont", code is "test", and project name is "Soil microcosms - Pangenomics"

**Comment by paczian** [comment]
Hey Tom,

I updated the code and restarted the server. The error is that it is expecting a FASTA file and does not have one. If the FASTA file is optional now, there need to be some minor changes to the code to not break at that point.

Cheers
Tobi

**Comment by paczian** [comment]
I have deleted the empty fasta file in that project and now you should be able to view it. The line that calls `touch fastaFile` in bottleroutes_multi needs to be removed.

**Comment by paczian** [comment]
Ah, I was wrong, this had already been changed. So if you create a new project without a fasta file it will just work. This was only due to the code not being up to date.
