### ISSUE TITLE
Anvio-sever need to reload webpage after creating a project

### ISSUE THREAD

**Issue by tdelmont** [meren/anvio#293]
I don't know if it is only with my laptop, but when creating a project, it goes from 0% to 100%, and then nothing happens, until I reload the page, then it works perfectly. If reproducible, any way to fix this little bug?
Thanks a lot

PS: I will test the server with many dataset types, and probably write a lot of issues in the coming days. So first I apology for the extra work, and second I want to thank all people involved in fixing them!

Tom

**Comment by meren** [comment]
At this point Tobi is the only one who is going to be involved fixing them, so we can thank him directly :)

**Comment by paczian** [comment]
I am not able to reproduce this, but I think I know what happens. When the upload is finished (the bar is at 100%) the interactive object is created. Depending on the amount of data, this might take some time. During this time the progress bar will remain and the page will automagically reload once the process is complete.

How long did you wait? You should not be hitting a timeout (which is around 5 minutes I think), but if so, you would be able to see it in the console. You can open that by pressing meta + apple + J or through the menu View -> Developer -> Javascript Console

**Comment by tdelmont** [comment]
It seems to be working just fine now.
