### ISSUE TITLE
Anvio-server - sharing a project

### ISSUE THREAD

**Issue by tdelmont** [meren/anvio#296]
Hi Tobias,
when sharing a project, it works just fine when making it public but does not work when we want just to create a link to share with people.
see error log:

<img width="1919" alt="screen shot 2016-01-28 at 9 34 13 am" src="https://cloud.githubusercontent.com/assets/8332889/12649074/9aed88a4-c5a2-11e5-9e13-8c07122f05e3.png">

Thanks

tom

**Comment by paczian** [comment]
fixed in #297
