### ISSUE TITLE
Anvio-server - error when loading my "gut" project

### ISSUE THREAD

**Issue by tdelmont** [meren/anvio#302]
Hi,
here is an error when I tried to load a new project I made (gut):

![screen shot 2016-01-29 at 10 59 29 am](https://cloud.githubusercontent.com/assets/8332889/12682133/8d2a4e8e-c677-11e5-8981-55c3665f5d11.png)

Tom

**Comment by meren** [comment]
It will get fixed when Tobi updates the server.

Tobi, this is an error based on profile db version (I fixed it back last night (f3521c004f6bce8d7437fbdaa5c7840edb2d1b7f)). But it seems even when status returns an error we don't handle that. You can reproduce the error by changing the version number in tables.py by hand temporarily.
