### ISSUE TITLE
Anvio-server - cannot edit attributes

### ISSUE THREAD

**Issue by tdelmont** [meren/anvio#303]
Hi, in my project "30genomes" I have 30 layers, and I cannot access the "Edit attributes for multiple layers" boxes.

![screen shot 2016-01-29 at 11 09 20 am](https://cloud.githubusercontent.com/assets/8332889/12682456/27c75d50-c679-11e5-9764-744606ff80ba.png)

Tom

**Comment by meren** [comment]
Tom, this is more of an @ozcanesen question, but you should be able to scroll with your mouse or using your touchpad. Can't you?

**Comment by tdelmont** [comment]
No it is not working, and it is even worse with the other project I am working, where I have >100 layers:
![screen shot 2016-01-29 at 1 28 47 pm](https://cloud.githubusercontent.com/assets/8332889/12685871/44e8dff4-c68c-11e5-9882-02aaa63eb48c.png)

**Comment by meren** [comment]
Can you attach minimum amount of necessary files to reproduce this (the tree and the matrix file).

**Comment by tdelmont** [comment]
[Archive.zip](https://github.com/meren/anvio/files/110308/Archive.zip)

**Comment by tdelmont** [comment]
The inner tree is "tree-species", and the supp tree is "tree-individuals".
I wanted to share the anvi'server project but it is currently not working

**Comment by meren** [comment]
("minimum amount of necessary files to reproduce the problem" does not include two trees and a bunch of other irrelevant files).
