### ISSUE TITLE
Anvio-server - need to update the logo

### ISSUE THREAD

**Issue by tdelmont** [meren/anvio#304]
Hi this is for Meren:
need to update the logo during waiting time of loading:

![screen shot 2016-01-29 at 11 15 21 am](https://cloud.githubusercontent.com/assets/8332889/12682669/469f3a8a-c67a-11e5-85de-f16bf71c50a5.png)

**Comment by meren** [comment]
The new logo is here:

https://raw.githubusercontent.com/meren/meren.github.io/master/images/anvio-logo-simple.png

**Comment by meren** [comment]
(note to self and others)

**Comment by meren** [comment]
done.
