### ISSUE TITLE
Anvio-server - cannot share a project

### ISSUE THREAD

**Issue by tdelmont** [meren/anvio#305]
Currently, it is not working when trying to share (publicly or not) a project.
There is no error log but the screen becomes a bit great and nothing happens...

![screen shot 2016-01-29 at 1 00 26 pm](https://cloud.githubusercontent.com/assets/8332889/12685203/872c8432-c688-11e5-898e-5f6f6358dd22.png)
...

Tom

**Comment by paczian** [comment]
fixed by #310
