### ISSUE TITLE
Anvio-server - need more red flags when uploading wrong files

### ISSUE THREAD

**Issue by tdelmont** [meren/anvio#306]
Hi,
during the creation of a project, if you upload a file into a "tree" box that is not a tree file, we see nicely a red file saying it is not a tree.
However, this nice feature is not used for the other boxes.
For example, I could not create a project because the format of my files was not good (unacceptable characters / wrong naming of the cell A1 (should be "contig" for the matrix, and "samples" for the samples info). The wrong files were accepted but then the project was not created, without an explanation to the user regarding what went wrong.

Any way to improve that?

Tom

**Comment by paczian** [comment]
There are two levels of checking here. One is the basic sanity check in the UI (is it a FASTA file, is it a tree file, is it a tab-separated text file vs. an excel file). Then there is the second deeper check after the upload, which tries to initialise an actual interactive object. It seems the error from that is not fed back correctly to the UI.

Tom, could you send me some example files that are invalid so I can test?

**Comment by tdelmont** [comment]
Ok, here are some examples are created when the server response is unclear or missing:

1- wrong sample name in metadata file:
[Metadata_wrong.zip](https://github.com/meren/anvio/files/112674/Metadata_wrong.zip)
Note that in this case, the interface works but without the samples metadata info. But the user cannot know it is because names in metadata and data files are not compatible.

2- wrong A1 cell in data. Needs to be "contig". With this error we see a red flag, but the text is long and the flag disappears after 2seconds, so I could not read it entirely...

3- wrong data format. I changed one number in the matrix with the letter "T". It actually did not perturb anything but the location shows an empty case for the "T":
![screen shot 2016-02-01 at 11 39 25 am](https://cloud.githubusercontent.com/assets/8332889/12725491/9abd7d10-c8d8-11e5-9d18-c1d144bb4fa8.png)

4- wrong tree. The flag is perfect for this bug:
![screen shot 2016-02-01 at 11 42 37 am](https://cloud.githubusercontent.com/assets/8332889/12725578/0a21f78a-c8d9-11e5-8a58-3b954be4547d.png)

5- wrong format for the sample order file: 
[Wrong_order_format.zip](https://github.com/meren/anvio/files/112698/Wrong_order_format.zip)
Note that in this case, the interface works but without the samples metadata info. But the user cannot know it is because format in sample order file is incorrect. (I just replaced "newick" by "neewick")

I will try to test more possibilities.

Tom

**Comment by paczian** [comment]
I have addressed most of these in #318. The server is updated. The one thing that is difficult to do in the UI is the cross-reference between sample names / contig names across files. Maybe we should add that in the backend @meren?

**Comment by meren** [comment]
At the end of the upload compatibility of names across all files (the tree, matrices, and the FASTA, if available) are being [checked](https://github.com/meren/anvio/blob/master/anvio/bottleroutes_multi.py#L221) already:

![image](https://cloud.githubusercontent.com/assets/197307/12850055/695c3bcc-cbe8-11e5-8994-8b6894e6dfa7.png)

If we are handling that retval from line 228 properly at the interface, we are golden. I will check that quickly now.

**Comment by meren** [comment]
Perfect, we do handle that retval properly:

![image](https://cloud.githubusercontent.com/assets/197307/12850137/e99b2640-cbe8-11e5-8f6c-3f6396711b0d.png)

However, **the error message stays on the page to short**. I think these type of fatal errors should stay forever until the user clicks on them (which is the default behavior if there is no time-out value).

**Comment by paczian** [comment]
Ok, I added the option to all fatal error messages on the user page in #319. @tdelmont mentioned in his post that:
"1- wrong sample name in metadata file:
Metadata_wrong.zip
Note that in this case, the interface works but without the samples metadata info. But the user cannot know it is because names in metadata and data files are not compatible."

Indicating a silent failure. Are the sample info / order files included in the backend check?

**Comment by meren** [comment]
Yes! backend check literally creates a test copy of the interactive interface object. If nothing fails, it means everything will work, so we are on solid ground :)

Thank you very much, Tobi. I guess we are done with this issue.
