### ISSUE TITLE
Anvio-server - knowing when you are in a public project

### ISSUE THREAD

**Issue by tdelmont** [meren/anvio#307]
Hi,
when you open a link, would be nice to know if it is a public project, or just a shared link to a (currently) private project. This could be presented in the top left section of the interface, nearby your ID name (private/public in a box with some color code would be great, blue for private and green for public maybe).
Also, a link to the project description would be great, so people can learn more about the project they are looking at.

Tom

**Comment by meren** [comment]
I will second this with an additional point. For instance the first project here is shared:

![image](https://cloud.githubusercontent.com/assets/197307/12989826/9c312b32-d0cc-11e5-83e7-300c4782ce05.png)

Maybe we can put tiny twitter and facebook share buttons next to others buttons for shared projects?

2 cents.

**Comment by ozcanesen** [comment]
I also have minor enhancement idea about this, when user clicks a public project link it redirects to /app/index.html so user no longer can copy and share the link from address bar, which is a problem because i am sure somebody going to try to share /app/index.html

We can use '#' for this, /app/index.html#/public/<project> --> redirects to /public/<project> --> redirects to /app/index.html#/public/<project> again

So index.html page should check this and if there is a view cookie for this project it should not do anything, and it should redirect to /public/<project> if hashes are not match or there is no cookie view hash.

Also we can use iframes for this but it can be trouble.

Best,

**Comment by meren** [comment]
Good point.

> i am sure _somebody_

\*_everyone_

FTFY :p

**Comment by paczian** [comment]
I addressed this in #321. When you come in with a sharing link, the url will simply be preserved. Tom, do you think the URL would be an ok place to see this information, or should I add something into the user section as well? This would then only be seen by users being logged in and then using a link.

Oh, and I put in the facebook / twitter buttons ;)

**Comment by meren** [comment]
These are awesome changes, Tobi. Thank you! I think the social media buttons look very cute, and preserving the URL is a great solution for making sure people don't share 127.0.0.1-like stuff :)

I think we can even further improve the shared page experience. You know how there is a space when a user is logged in here which shows the home and logout button:

![image](https://cloud.githubusercontent.com/assets/197307/13010045/6ce2a894-d165-11e5-828e-5d83921c9308.png)

We can use this space to show (1) this is a public project by X, (2) put a button to popup the description of the project, and (3) another button to show project data files (similar to admin interface --and if those files can be downloaded altogether or individually, that would be very helpful for everyone to play with the data on their own computers and re-upload or adjust to their own purposes).

2 cents.

**Comment by paczian** [comment]
addressed in #326, let me know if that is what you were thinking of or if you would like to pixelpush / tweak it

**Comment by meren** [comment]
This is great, Tobi. Thank you. A couple of suggestions:

This is how it looks on my screen:

![image](https://cloud.githubusercontent.com/assets/197307/13124188/03211ada-d58e-11e5-9c03-62c3599166aa.png)

And this is how it looks when accessed publicly:

![image](https://cloud.githubusercontent.com/assets/197307/13124213/2b523bf6-d58e-11e5-8466-67fbc0dedea2.png)

I think a description button would have been awesome place to have (a popover window with the details of the project i.e. name, owner, and description).

I also think if we had a 'files' button, insted of a 'download' button there, which showed this in a popover:

![image](https://cloud.githubusercontent.com/assets/197307/13124476/aa4d08a0-d58e-11e5-8725-3d63296cf31b.png)

and allowed you to download all files with a button in this window, it would have been very elegant! :)

**Comment by paczian** [comment]
Hm, weird, it should be showing the gravatar icon next to the home button. As for the other suggestions, I’ll make the download button an info button that show that popup.

**Comment by paczian** [comment]
Addressed in #327
