### ISSUE TITLE
anvi-server version should be seen somewhere

### ISSUE THREAD

**Issue by meren** [meren/anvio#320]
Hi,

I think this could be a nice place for it, but they can be tiny:

![image](https://cloud.githubusercontent.com/assets/197307/12995960/2c3023f4-d0f1-11e5-9bba-493ee2f07961.png)

But we need to show both anvio version, and users db version. I made some changes (5a56e6d4353ce4cf0359b048ea6317f3aa0ae3ca), so both can be obtained easily via these two variables:

``` python
anvio.__version__
anvio.__users_db_version__
```

Thanks in advance, Tobi!

**Comment by paczian** [comment]
addressed in #321
