### ISSUE TITLE
gravatar?

### ISSUE THREAD

**Issue by meren** [meren/anvio#322]
OK. I know this is a luxury item :) But do you think it is worth to use gravatar to show user avatars and fall back to our current one if they don't have any?

Please feel free to WONTFIX me.

Best,

**Comment by paczian** [comment]
added in #326

**Comment by meren** [comment]
this is what's going on with this update, I don't understand why it is not working :(

![image](https://cloud.githubusercontent.com/assets/197307/13155782/5bfff59e-d64d-11e5-8a7c-dd3776297c89.png)

It seems the returned image from gravatar is a 1px.

**Comment by meren** [comment]
Sorry, Tobi, it is all working. I didn't realize it was my fault (this Chrome plugin was blocking Gravatar). I apologize, and thank you very much for this addition!

![image](https://cloud.githubusercontent.com/assets/197307/13176349/95ccc2c4-d6df-11e5-9511-05536317f0be.png)
