### ISSUE TITLE
Suggesting a tiny improvement

### ISSUE THREAD

**Issue by meren** [meren/anvio#328]
This is absolutely awesome, Tobi:

![image](https://cloud.githubusercontent.com/assets/197307/13155828/9b50bd96-d64d-11e5-8a96-09584e821f43.png)

Thank you for bearing with me :) I was wondering could it be also possible to have a link next to "Project files" that says "download all", which downloads a zipped directory (like project_name.zip) with all files.

Thank you for your consideration!

**Comment by paczian** [comment]
added in #338
