### ISSUE TITLE
anvi-server issue scrolling layer section in the scree

### ISSUE THREAD

**Issue by tdelmont** [meren/anvio#331]
Hi,
I continue having issues seeing the "edits attributes for multiple layers" in the "layer" section of the interface. When scrolling the screen down, most of the "edits attributes for multiple layers" is not visible, and I can barely select colors, etc.
This seems to be an issue associated with projects having a large number of layers.

See example:
 
<img width="487" alt="screen shot 2016-02-19 at 1 27 28 pm" src="https://cloud.githubusercontent.com/assets/8332889/13186601/8ea25ef0-d70c-11e5-8426-7d2e408898bf.png">

Tom

**Comment by meren** [comment]
This is not an anti-server issue. More like a general interface problem. I am tentatively assigning it to Özcan, but I will try to take a look at it myself.

**Comment by ozcanesen** [comment]
This is a anvi server issue related with multiUser div, if you run $('#multiUser').remove(); on the chrome web console, problem disappears. We should change the way we put that div on the sidebar.

**Comment by ozcanesen** [comment]
Hey Meren, we need better fix for this, because manual interface looks like this:

![image](https://cloud.githubusercontent.com/assets/940884/13206639/e9ebc35a-d90a-11e5-9afe-a2984b8e9140.png)

**Comment by meren** [comment]
I know :( I had to do something for this because it was literally stopping me from editing something. You're right, I shouldn't have closed the issue.

**Comment by paczian** [comment]
This problem is a side-effect of the project information being shown even when no user is logged in (for public projects). I will take a look at this.

**Comment by meren** [comment]
We have a variable that keeps track of which mode we're in. Whether it is
server, full, or refine.

If we are not in server mode, that div can be 'bot pushed' :)

**Comment by meren** [comment]
I meant 'not pushed'.

**Comment by paczian** [comment]
I added a fix in #333
