### ISSUE TITLE
multiUser div creates an empty space above the drawing area

### ISSUE THREAD

**Issue by ozcanesen** [meren/anvio#334]
Hi Tobi,

Sidebar and the drawing area have fixed positions on the page but multiUser div is not. So it moves everything to a new line and creates an empty space, apart from visual glitch it has side effects too, area zoom with shift key does not work correctly, also issue #331 is another side effect. I think this div should be a child of the sidebar or should has fixed position.

Thanks.

Example sreenshot:
![image](https://cloud.githubusercontent.com/assets/940884/13339880/9b54c214-dc34-11e5-9419-626991a0ccaf.png)

**Comment by paczian** [comment]
fixed in #336
