### ISSUE TITLE
sample tree is missing when opening a project in anvio or anvi-server

### ISSUE THREAD

**Issue by tdelmont** [meren/anvio#344]
Hi,

when we save a state, and then load a project with anvi'o or anvi-server, then all saved info loads expect the layers' tree.

Would be great to fix this little bug!

tom

**Comment by meren** [comment]
Tom is talking about this tree, Ozcan:

![image](https://cloud.githubusercontent.com/assets/197307/14032707/c878f6f2-f1e2-11e5-95c4-efcf3a4cb354.png)

:)
