### ISSUE TITLE
Error running mini test

### ISSUE THREAD

**Issue by mprichardson** [meren/anvio#345]
Dear Meren,

I have just installed anvio on a clean install of ubuntu 14.04 LTS, and I have been encountering a problem running the mini test. 

I followed previous articles on here, and anvi-profile worked correctly. 

I received an error, which I did not save (I thought I could go back!) The error talked about mismatched names in one of the early lines of the mini test. The error appeared almost immediately after beginning the mini test. The error contained a location in the pysam/samtools directory, and I looked at the version number, and pysam has been updated on march 1st to a new version (0.9.0).

I installed pysam 0.8.4, and the mini-test worked perfectly again.

Since I cannot find the specific error, all I can do that there is an error being created by the new version of pysam, which is the default installed by the shell script provided. 

Thanks,

Miles

**Comment by meren** [comment]
Hi Miles,

I just updated the setup.py and the [Ubuntu installation notes](https://gist.github.com/meren/f1e674f774a30a209d82) to make sure we don't automatically install the latest version of pysam.

Thank you very much!
