### ISSUE TITLE
anvi'server download project link should download all files

### ISSUE THREAD

**Issue by meren** [meren/anvio#353]
When the download button next to 'project files' is clicked, the archive prepared for download does not contain profile.db or samples.db (if there is any):

![image](https://cloud.githubusercontent.com/assets/197307/14539286/619f46fc-0245-11e6-8de0-b6edb1de2d25.png)

It is OK to not show them in the list of individual downloads, since they are useless by themselves, but putting them into the archive is important if the user wants to download the project, because they hold key information about the state, and the bins user may have stored in the project :)

I am not assigning this to anyone, but I will mention @gkmngrgn here in case he wants to play with this.

Best,

**Comment by gkmngrgn** [comment]
@meren hi, I think, it may not good idea to insert SQLite file to a json object to send to the frontend from the backend. Other files are text, so we can dump SQLite files as profile.sql, samples.sql. For example, in ``usermgmt.py#809``:

``` python
        # get files of the project
        path = self.users_data_dir + '/userdata/'+ user["path"] + '/' + project['path'] + "/"
        filenames = [
            'dataFile', 'fastaFile', 'treeFile', 'additionalDataFile', 'samplesInformationFile', 'samplesOrderFile',
            'profile.db', 'samples.db']
        dataFiles = {}
        for fn in filenames:
            fullfn = path + fn
            if os.access(fullfn, os.R_OK):
                if os.path.splitext(fn) == '.db':
                    db_con = sqlite3.connect(fullfn)
                    dataFiles['{}.sql'.format(fn)] = '\n'.join(db_con.iterdump())
                else:
                    with open(fullfn, 'r') as content_file:
                        dataFiles[fn] = content_file.read()
            else:
                dataFiles[fn] = None
```

**Comment by meren** [comment]
Hi @gkmngrgn!

It is the best if we transfer `profile.db` and `samples.db` as is, so the user can fire up the interactive interface with one command in the directory of downloads.

If we dump them into a text file, we would have to recreate those db's at the client side first if we want to make them usable by anvi'o. Neither samples.db nor profile.db from the server will exceed a couple of KBs at the end.

What concern makes you suggest this?


Best wishes,

**Comment by gkmngrgn** [comment]
@meren I don't know that there is a way to make db files as json serializable. It's giving UnicodeDecodeError.

**Comment by meren** [comment]
This works beautifully! Thank you very much, @gkmngrgn!
