### ISSUE TITLE
bug in the interactive interface

### ISSUE THREAD

**Issue by tdelmont** [meren/anvio#356]
Hi, I just created a new project on the anvi-server, 
and I realized that it is no longer possible to change the color of names below the tree:
(these names correspond to text in the metadata on the side of the tree)
Clicking on the box just does not work anymore.

![screen shot 2016-04-25 at 10 10 18 am](https://cloud.githubusercontent.com/assets/8332889/14788534/f473620c-0acd-11e6-90f1-f69813248daf.png)

Tom

**Comment by meren** [comment]
Tom, I edited out the link from your report.

The best way to report these issue is to use the mini test, so anyone can replicate it easily.

**Comment by meren** [comment]
@ozcanesen, I just confirmed that the problem is reproducible with mini_test :)

**Comment by meren** [comment]
Tom, if you go to anvi-server and refresh your project display page, this will be fixed.

**Comment by meren** [comment]
Thank you, @ozcanesen!
