### ISSUE TITLE
Improvements in SNV profiler and reporting

### ISSUE THREAD

**Issue by tdelmont** [meren/anvio#364]
Hi, I very slowly realize that some "SNV" types are difficult to extract from the current report tables of NTs (anvi'o 2.0.0)

I suggest to classify positions into 4 categories (I think those 4 represent the entire panel but might have missed extra-ones so far):

1- stable in the metagenome and consistent with the reference sequence (e.g., genome). Departure is currently "0". This is not a SNV.

2- stable in the metagenome but different from the reference genome. Departure is currently very close to "1". This is not a SNV either, but provides information regarding distances between references sequences and metagenomic data. Preliminary results suggest it might represent an important index in the future.

3- variable with one nucleotide/aa consistent with the reference sequence. Departure is ranges from close to "0" to close to "1". This is the classic SNV!

4- variable without being consistent with the reference sequence. Departure is currently close to "1". This is not a SNV from the reference sequence perspective, but a SNV from the metagenomic perspective... So it might need a distinct naming?

At this point, it is not easy for me to differentiate types 2 and type 4 from the table. Missing might be a column providing the frequency of the most abundant NT (named n1 in the anvi'o publication). Or, in the best case scenario, a column with position type from 1 to 4 would be great, no? If this can be processed during profiling. 

Hope it is not too confusing. I think adding those columns will improve the user's ability to inventory genomic heterogeneity types in environmental surveys.

Tom

**Comment by tdelmont** [comment]
this is a very concrete example of the problem between types 2 and 4:

![screen shot 2016-05-17 at 12 51 27 pm](https://cloud.githubusercontent.com/assets/8332889/15333157/28c762a8-1c2e-11e6-8dfd-7229acc86362.png)

**Comment by meren** [comment]
I will re-introduce n1n2_ratio which will address all of these, in conjunction with the departure of consensus metric.

**Comment by meren** [comment]
@tdelmont 6a78ba5ef8fe7a0afe990c071669b10ed678c015 should address this. Please update your codebase, test the new output, make sure it is resolved, and then close the issue.

**Comment by meren** [comment]
OK. We just figured we need another column, `departure_from_dominant`, which will be similar to `departure_from_consensus`, but will be critical in situations where the consensus is not the dominant allele. Because Tom just erased the board, I will not be able to include a figure.

Just another question: I think we should call `departure_from_consensus` as `departure_from_reference`. I will probably change this in the code, too.

**Comment by tdelmont** [comment]
what about 4 columns with consistent names:
reference (NT or AA ref)
consensus (dominant NT or AA)
departure from reference
departure from consensus

Tom

**Comment by meren** [comment]
OK. This makes sense. I will look into this soon.

**Comment by meren** [comment]
It is time to try it, @tdelmont!

**Comment by meren** [comment]
so far I've added the following parameters:

* `--genes-of-interest`
* `--max-deparature-from-reference`
* `--min-departure-from-consensus`
* `--max-departure-from-consensus`

**Comment by tdelmont** [comment]
Both consensus and reference columns seem to be working perfectly.

Thanks Meren!
