### ISSUE TITLE
A fix in terminology in SNV profiles: consensus -> reference

### ISSUE THREAD

**Issue by meren** [meren/anvio#367]
So we map things to a reference, and recover SNV frequencies.

We have been calling the base at a given nucleotide position in the reference "consensus". Clearly it is not a very good idea. Why we called it consensus instead of reference has a history: in the very early days of anvi'o (like, right after the 'nam war when we started this project), we used to keep track of the dominant base at each variable site, and the database column to store them was called consensus, which makes sense. Then we decided that it would be much better if each variable position knew about the reference, instead of the consensus, because the consensus could be computed easily from frequencies, but the reference information was not so easy to recover. We change the code that filled that information, without changing the name. After all this time, while we started discussing the future of our SNV reports under #364, we realized we need consensus, and reference. So here we will make that change we didn't do at the beginning. And, friends, this is how BS emerges in large codebases. This time we will fix it! I will tag each commit with this issue number, and then go back to implementing what we need to address #364. This is going to be good.

There is one bad news though: the profile db version number will have to go from 13 to 14. But I will also put a script into the sandbox folder to upgrade existing profile dbs of v13.

**Comment by meren** [comment]
All changes are made, and the upgrade script is in place!


Here is a test with the merged database of `mini_test`:

```
$ anvi-gen-variability-profile -p PROFILE.db -c CONTIGS.db -C CONCOCT -b Bin_1
Auxiliary Data ..............................................: Found: CONTIGS.h5 (v. 1)
Contigs DB ..................................................: Initialized: CONTIGS.db (v. 5)

Config Error: It seems the database 'PROFILE.db' was generated when your client was at version
              13, however, your client now is at version 14. Which means this database file
              cannot be used with this client anymore and needs to be upgraded to the version
              14 :/ That being said, you may not need to re-create this database if there is a
              script to upgrade this database from v13 to v14. Please feel free to get in
              touch with the anvi'o developers (they will be happy to hear from you).


$ anvi-script-upgrade-profile-db-v13-to-v14 PROFILE.db

WARNING
===============================================
This script will try to upgrade your profile database. If things go south, you
will end up having to re-profile your data :/ It may be a good idea to back it
up first. If you already backed your stuff or you are certain that it will work,
or if you are a lucky person in general, press ENTER to continue. If you want to
cancel the upgrade, press CTRL+C now. If you want to avoid this message the next
time, use "--just-do-it" flag.

Press ENTER to continue...

* Database successfully upgraded to version 14!

$ anvi-gen-variability-profile -p PROFILE.db -c CONTIGS.db -C CONCOCT -b Bin_1
Auxiliary Data ..............................................: Found: CONTIGS.h5 (v. 1)
Contigs DB ..................................................: Initialized: CONTIGS.db (v. 5)
Variability data ............................................: 52 entries in 38 splits across 3 samples
Samples in the profile db ...................................: s204_6M, s204_7M, s204_9M
Num splits of interest ......................................: 18
Remaining entries after "splits of interest" filter .........: 28 (filter removed 24 entries)
Total number of variable positions in samples ...............: s204_6M: 4; s204_7M: 0; s204_9M: 24
Num positions to keep from each split .......................: (all positions)
Num entries reported ........................................: 28
Output File .................................................: variability.txt
Num nt positions reported ...................................: 28
```

@tdelmont, can you test / confirm and close this issue?


Thanks!

**Comment by tdelmont** [comment]
The new variability tables seem to work perfectly, the the capacity to select SNVs based on either the consensus or the reference. Thanks Meren!
