### ISSUE TITLE
default IP address of 0.0.0.0 is put into static export bins table link

### ISSUE THREAD

**Issue by ctb** [meren/anvio#386]
When running remotely (on e.g. an AWS instance) & not giving an IP address, the default IP address of 0.0.0.0 is passed through to the bins static table export, which doesn't work. So then you need to set -I.

**Comment by meren** [comment]
In such situations it is best to specify an IP address, since everything I did about this before broke things for somewhere else, especially on machines with multiple network interfaces :/

**Comment by ctb** [comment]
Thinking about it, this should be something that (at least for this
problem) can be handled by looking at the host that is being asked
for in the HTTP header ('Host:').  At the worst, JavaScript should be
able to give you the right hostname...

**Comment by meren** [comment]
Well, I think this would work :) Solid suggestion! Thank you very much.

**Comment by ctb** [comment]
I'd submit a PR but I don't know js, sorry :)

**Comment by ctb** [comment]
Oh! nice work!

**Comment by meren** [comment]
Please let me know if this works for you. Thank you again!
