### ISSUE TITLE
When specifying a port with -P that can't be bound, port+1 is attempted

### ISSUE THREAD

**Issue by ctb** [meren/anvio#387]
This is kind of weird for situations where I'm specifying port 80 and for whatever reasons it can't be bound, because then anvio tries to bind port 81.  I think if -P is specified but can't be bound, anvio should crash rather than attempt port + 1.

**Comment by meren** [comment]
Oh, yes, you're absolutely right.

**Comment by meren** [comment]
This should be addressed now.

Thank you very much for the report, Titus!
