### ISSUE TITLE
Something is wrong with anvi-rename-bins

### ISSUE THREAD

**Issue by tdelmont** [meren/anvio#392]
Hi,

I just realize that if I run "anvi-rename-bins" multiple times on the same collections, a good portion of the bins get "lost in translation" each time starting from the second run.

Here is the command I used first:
"anvi-rename-bins -c CONTIGS.db -p PROFILE.db --use-SCG-averages --call-MAGs --size-for-MAG 2 --max-redundancy-for-MAG 100 -C CONCOCT_c10 --prefix X --report-file NAMING_X"

And here is the command line I used after that:

"anvi-rename-bins -c CONTIGS.db -p PROFILE.db --use-SCG-averages --call-MAGs --size-for-MAG 0.5 --max-redundancy-for-MAG 100 -C CONCOCT_c10 --prefix X --report-file NAMING_X"

Note that the largest bins are lost first. Could it be because of the " --size-for-MAG 0.5" flag?

Tom

**Comment by tdelmont** [comment]
Ok, I did some more test, and it is not about the "0.5" in --size-for-MAG:

here is the example I did from my current project:

1-run 1:

anvi-rename-bins -c CONTIGS.db -p PROFILE.db --use-SCG-averages --call-MAGs --size-for-MAG 2 --max-redundancy-for-MAG 100 -C CONCOCT_c10 --prefix X_M-P --report-file NAMING_ORAL_M-P
Auxiliary Data ...............................: Found: CONTIGS.h5 (v. 1)
Contigs DB ...................................: Initialized: CONTIGS.db (v. 6)

WARNING
===============================================
Previous entries for "CONCOCT_c10" is being removed from "collections_info,
collections_of_contigs, collections_of_splits, collections_bins_info"

Collections ..................................: CONCOCT_c10 annotations for 14937 splits have been successfully added to the database at "PROFILE.db".
Rename .......................................: Renaming is done for 140 bins in collection "CONCOCT_c10".
Report .......................................: NAMING_X_M-P

2-run 2:

anvi-rename-bins -c CONTIGS.db -p PROFILE.db --use-SCG-averages --call-MAGs --size-for-MAG 2 --max-redundancy-for-MAG 100 -C CONCOCT_c10 --prefix X_M-P --report-file NAMING_X_M-P
Auxiliary Data ...............................: Found: CONTIGS.h5 (v. 1)
Contigs DB ...................................: Initialized: CONTIGS.db (v. 6)

WARNING
===============================================
Previous entries for "CONCOCT_c10" is being removed from "collections_info,
collections_of_contigs, collections_of_splits, collections_bins_info"

Collections ..................................: CONCOCT_c10 annotations for 423 splits have been successfully added to the database at "PROFILE.db".
Rename .......................................: Renaming is done for 17 bins in collection "CONCOCT_c10".
Report .......................................: NAMING_X_M-P

**Comment by tdelmont** [comment]
Ok, the problem is that when anvi rename X by X, then this bin disappears. 
Only bins for which name changes remain...
I tested it multiple time.

**Comment by meren** [comment]
OK. The user will no longer be able to overwrite the contents of a collection, and they are going to be forced to create a new one.

I also will add another program to delete collections. So they can try multiple times until they get it right.
