### ISSUE TITLE
anvi-import-taxonomy requires fixed file names centrifuge import

### ISSUE THREAD

**Issue by fbreitwieser** [meren/anvio#393]
Hi Meren Lab, thanks for your great software, I'm exploring it more and more!

I've very  minor issue with anvi-import-taxonomy: it checks for the file names, and requires them to be centrifuge_report.tsv and centrifuge_hits.csv . It would be nice if the script allowed custom file names, and  just checks the extension or position of the files.

**Comment by meren** [comment]
Dear Florian, thank you very much for giving it a try!

I apologize for this inconvenience. It will take a bit of time, but we will fix this issue. Thank you for the report!

**Comment by fbreitwieser** [comment]
Hi Meren, thanks for the quick answer! No big inconvenience, there are easy workarounds

**Comment by fbreitwieser** [comment]
Oh, I'm sorry I didn't check beforehand, I'll close as duplicate of #376 !
