### ISSUE TITLE
Support prodigal v2.6.3

### ISSUE THREAD

**Issue by fbreitwieser** [meren/anvio#394]
Prodigal v2.6.3 is available, but currently not supported in anvio (v2.60 and v2.6.2 are).

anvi-gen-contigs-database seems to work fine with it, at least on one data set I was running with it (after duping the version number).

https://github.com/hyattpd/prodigal/releases/

**Comment by meren** [comment]
Thank you very much, Florian!

I will test it, and add it in the list of versions anvi'o is fine with immediately after ISME! :)


Best,

**Comment by fbreitwieser** [comment]
Thank you :)

**Comment by meren** [comment]
sorry for the late response. I finally could test it properly and do this little change.

**Comment by meren** [comment]
of course, it will be effective with the next stable release unless you are using the master repository :)
