### ISSUE TITLE
Pangenome calculating 'Num genes per kbp' erroneously for internal bins

### ISSUE THREAD

**Issue by AstrobioMike** [meren/anvio#397]
Hey there!

Subject says it all. Number of genes per kbp is coming out way lower than it should be, but it only seems to be a problem on internal genomes and not the external ones i incorporate. 

Cheers!
-mike

**Comment by meren** [comment]
You know what? This explains a lot! :p

Thank you for the report, and a fix is on the way.

It would be lovely if you can confirm it is fixed. Thanks a lot!

**Comment by AstrobioMike** [comment]
Yeppers! That fixed it! 

Thanks!
